services:
  rampardos:
    image: ghcr.io/lenisko/rampardos:latest
    container_name: rampardos
    restart: unless-stopped
    tty: true
    user: "${PUID:-0}:${PGID:-0}"
    volumes:
      - ./Cache:/app/Cache
      - ./Templates:/app/Templates
      - ./TileServer:/app/TileServer
      - ./Markers:/app/Markers
    environment:
      PORT: ${PORT:-9000}
      HOSTNAME: ${HOSTNAME:-0.0.0.0}
      TILE_CACHE_MAX_AGE_MINUTES: ${TILE_CACHE_MAX_AGE_MINUTES:-10080}
      TILE_CACHE_DELAY_SECONDS: ${TILE_CACHE_DELAY_SECONDS:-3600}
      STATIC_CACHE_MAX_AGE_MINUTES: ${STATIC_CACHE_MAX_AGE_MINUTES:-10080}
      STATIC_CACHE_DELAY_SECONDS: ${STATIC_CACHE_DELAY_SECONDS:-3600}
      STATIC_MULTI_CACHE_MAX_AGE_MINUTES: ${STATIC_MULTI_CACHE_MAX_AGE_MINUTES:-60}
      STATIC_MULTI_CACHE_DELAY_SECONDS: ${STATIC_MULTI_CACHE_DELAY_SECONDS:-900}
      MARKER_CACHE_MAX_AGE_MINUTES: ${MARKER_CACHE_MAX_AGE_MINUTES:-1440}
      MARKER_CACHE_DELAY_SECONDS: ${MARKER_CACHE_DELAY_SECONDS:-3600}
      PREVIEW_LATITUDE: ${PREVIEW_LATITUDE:-51.5165753}
      PREVIEW_LONGITUDE: ${PREVIEW_LONGITUDE:--0.1543177}
      ADMIN_USERNAME: ${ADMIN_USERNAME:-}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-}
      PYROSCOPE_SERVER_ADDRESS: ${PYROSCOPE_SERVER_ADDRESS:-}
      PYROSCOPE_APPLICATION_NAME: ${PYROSCOPE_APPLICATION_NAME:-rampardos}
      PYROSCOPE_API_KEY: ${PYROSCOPE_API_KEY:-}
      PYROSCOPE_BASIC_AUTH_USER: ${PYROSCOPE_BASIC_AUTH_USER:-}
      PYROSCOPE_BASIC_AUTH_PASSWORD: ${PYROSCOPE_BASIC_AUTH_PASSWORD:-}
      PYROSCOPE_MUTEX_PROFILE_FRACTION: ${PYROSCOPE_MUTEX_PROFILE_FRACTION:-5}
      PYROSCOPE_BLOCK_PROFILE_RATE: ${PYROSCOPE_BLOCK_PROFILE_RATE:-5}
      PYROSCOPE_LOGGER: ${PYROSCOPE_LOGGER:-false}
      RENDERER_POOL_SIZE: ${RENDERER_POOL_SIZE:-4}
      STYLE_POOL_SIZE: ${STYLE_POOL_SIZE:-}
      RENDERER_TIMEOUT_SECONDS: ${RENDERER_TIMEOUT_SECONDS:-15}
      RENDERER_WORKER_LIFETIME: ${RENDERER_WORKER_LIFETIME:-500}
    ports:
      - ${PORT:-9000}:9000
    deploy:
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 1G
